/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import { DissolveMaterial, DissolveMaterialProps } from "./DissolveMaterial";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js";

type GLTFResult = GLTF & {
	nodes: {
		tableLarge: { geometry: THREE.BufferGeometry };
	};
	materials: {
		"BrownDark.074": THREE.MeshStandardMaterial;
	};
};
export function Table(
	props: JSX.IntrinsicElements["group"] &
		DissolveMaterialProps & { dissolveVisible: boolean }
) {
	const group = useRef<THREE.Group>(null!);
	const { nodes, materials } = useGLTF(
		"https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/table-wood/model.gltf"
	) as GLTFResult;
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh geometry={nodes.tableLarge.geometry} rotation={[Math.PI / 2, 0, 0]}>
				<DissolveMaterial
					baseMaterial={materials["BrownDark.074"]}
					visible={props.dissolveVisible}
					onFadeOut={props.onFadeOut}
					color="#7f532f"
				/>
			</mesh>
		</group>
	);
}

useGLTF.preload(
	"https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/table-wood/model.gltf"
);
